In [3]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline 

In [5]:
df=pd.read_csv('new_dataframe _without_op.csv')

In [7]:
dft=pd.read_csv('target.csv')

RFE

In [19]:
#recursively removes features 
#train and find feature performance repeatedly and eliminate 
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score

In [15]:
X=df

In [16]:
y=dft

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0) 
X_train.shape,X_test.shape

((339, 169), (113, 169))

In [20]:
### Feature selection by feature importance of random forest classifier 
sel=SelectFromModel(RandomForestClassifier(n_estimators=100,random_state=0,n_jobs=-1))
sel.fit(X_train,y_train)
sel.get_support()

C:\Users\VIDYA\Anaconda3\lib\site-packages\sklearn\feature_selection\from_model.py:197: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.estimator_.fit(X, y, **fit_params)


array([False, False, False, False,  True, False,  True, False, False,
       False,  True, False, False,  True, False,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False,  True,  True, False, False, False, False, False, False,
       False,  True,  True, False, False,  True,  True, False,  True,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True,  True,  True, False, False, False,  True,
       False,  True, False,  True, False,  True, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False,  True, False,  True, False, False, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False,  True, False, False, False,  True, False, False,
        True, False,

In [21]:
X_train.columns

Index(['age', 'sex', 'height', 'weight', 'qrs_duration', 'p-r_interval',
       'q-t_interval', 't_interval', 'p_interval', 'qrs',
       ...
       'KT', 'KU', 'KV', 'KY', 'KZ', 'LA', 'LD', 'LE', 'LF', 'LG'],
      dtype='object', length=169)

In [22]:
features=X_train.columns[sel.get_support()]


In [23]:
features

Index(['qrs_duration', 'q-t_interval', 'T', 'heart_rate', 'r_wave', 's_wave',
       'BY', 'CC', 'CJ', 'DB', 'DD', 'DM', 'DN', 'DZ', 'EA', 'EB', 'GF', 'GJ',
       'GK', 'GL', 'GP', 'GU', 'GY', 'HA', 'HL', 'HR', 'HT', 'ID', 'IH', 'IN',
       'IR', 'IV', 'JB', 'JD', 'JG', 'JK', 'JL', 'JM', 'JN', 'JP', 'JR', 'JV',
       'JY', 'JZ', 'KA', 'KC', 'KD', 'KH', 'KI', 'KJ', 'KK', 'KS', 'KU', 'LE',
       'LG'],
      dtype='object')

In [24]:
len(features)

55

In [26]:
np.mean(sel.estimator_.feature_importances_)

0.005917159763313609

In [27]:
sel.estimator_.feature_importances_

array([0.00386757, 0.00107774, 0.00458403, 0.00206229, 0.01651801,
       0.00470552, 0.01127994, 0.00409614, 0.00502839, 0.00449442,
       0.00903875, 0.00506501, 0.00411397, 0.05689658, 0.00081112,
       0.00777135, 0.00619443, 0.00459873, 0.00402124, 0.00241455,
       0.00296838, 0.00025961, 0.00311173, 0.00406916, 0.00235476,
       0.00228154, 0.00139766, 0.00439518, 0.00340431, 0.00501289,
       0.00087865, 0.00032571, 0.00363025, 0.00190347, 0.00724371,
       0.00421813, 0.00012561, 0.00765512, 0.01058267, 0.00407881,
       0.00192249, 0.0002899 , 0.00530812, 0.00173359, 0.00311825,
       0.0054365 , 0.02430298, 0.01268015, 0.00233628, 0.00301777,
       0.0059423 , 0.00882829, 0.00548761, 0.00646671, 0.01022027,
       0.00975831, 0.00447563, 0.00140484, 0.00374238, 0.00534427,
       0.00421662, 0.00165382, 0.00254608, 0.00304298, 0.00448969,
       0.00180771, 0.00435465, 0.00308532, 0.00397593, 0.00292478,
       0.00083993, 0.00322577, 0.0073696 , 0.0031354 , 0.01543

In [28]:
X_train_rfc=sel.transform(X_train)
X_test_rfc=sel.transform(X_test)

In [35]:
def run_randomForest(X_train,X_test,y_train,y_test):
    clf=RandomForestClassifier(n_estimators=100,random_state=0,n_jobs=-1)
    clf.fit(X_train,y_train)
    y_pred=clf.predict(X_test)
    print('Accuracy: ',accuracy_score(y_test,y_pred))


In [36]:
%%time
run_randomForest(X_train_rfc,X_test_rfc,y_train,y_test)

C:\Users\VIDYA\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


Accuracy:  0.7079646017699115
Wall time: 413 ms


In [37]:
%%time
run_randomForest(X_train,X_test,y_train,y_test)

C:\Users\VIDYA\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


Accuracy:  0.6991150442477876
Wall time: 383 ms


In [38]:
###RECURSIVE FEATURE ELIMINNATION 

In [102]:
from sklearn.feature_selection import RFE
sel=RFE(RandomForestClassifier(n_estimators=100,random_state=0,n_jobs=-1),n_features_to_select=55)
sel.fit(X_train,y_train)

C:\Users\VIDYA\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


RFE(estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=0, verbose=0, warm_start=False),
  n_features_to_select=65, step=1, verbose=0)

In [103]:
sel.get_support()

array([ True, False, False, False,  True, False,  True,  True,  True,
       False,  True, False,  True,  True, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False,  True,  True, False, False, False,  True, False, False,
       False,  True,  True, False, False, False, False,  True, False,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True, False,  True, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False,  True, False,  True,  True, False, False, False, False,
        True, False,  True, False,  True, False, False, False,  True,
       False, False,  True, False, False, False,  True, False,  True,
        True, False,

In [104]:
features=X_train.columns[sel.get_support()]

In [105]:
features

Index(['age', 'qrs_duration', 'q-t_interval', 't_interval', 'p_interval', 'T',
       'QRST', 'heart_rate', 'r_wave', 'BY', 'CC', 'CJ', 'CO', 'DB', 'DD',
       'DP', 'EA', 'EB', 'EF', 'GF', 'GJ', 'GK', 'GL', 'GO', 'GP', 'GT', 'GU',
       'GV', 'GY', 'HA', 'HL', 'HR', 'HT', 'HU', 'ID', 'IF', 'IH', 'IN', 'IR',
       'IV', 'JA', 'JB', 'JD', 'JG', 'JK', 'JL', 'JM', 'JN', 'JP', 'JR', 'JV',
       'JY', 'JZ', 'KA', 'KC', 'KH', 'KI', 'KJ', 'KK', 'KR', 'KS', 'KU', 'KV',
       'LE', 'LG'],
      dtype='object')

In [106]:
len(features)

65

In [107]:
X_train_rfe=sel.transform(X_train)
X_test_rfe=sel.transform(X_test)

In [108]:
%%time
run_randomForest(X_train_rfe,X_test_rfe,y_train,y_test)

C:\Users\VIDYA\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


Accuracy:  0.6902654867256637
Wall time: 425 ms


In [109]:
%%time
run_randomForest(X_train,X_test,y_train,y_test)

C:\Users\VIDYA\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


Accuracy:  0.6991150442477876
Wall time: 461 ms


In [76]:
### Feature Selection by GradientBoost tree Importance 

In [77]:
from sklearn.ensemble import GradientBoostingClassifier

In [78]:
sel=RFE(RandomForestClassifier(n_estimators=100,random_state=0),n_features_to_select=30)
sel.fit(X_train,y_train)

C:\Users\VIDYA\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


RFE(estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False),
  n_features_to_select=30, step=1, verbose=0)

In [66]:
sel.get_support()

array([False, False, False, False,  True, False,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False,  True,  True, False, False, False, False, False, False,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
        True, False,

In [79]:
features=X_train.columns[sel.get_support()]

In [80]:
features

Index(['qrs_duration', 'q-t_interval', 'heart_rate', 'CJ', 'DB', 'DD', 'EA',
       'EB', 'GJ', 'GL', 'GU', 'HA', 'HR', 'HT', 'IV', 'JB', 'JG', 'JK', 'JL',
       'JN', 'JP', 'JR', 'JY', 'JZ', 'KA', 'KH', 'KK', 'KS', 'LE', 'LG'],
      dtype='object')

In [ ]:
%%time
run_randomForest(X_train_rfe,X_test_rfe,y_train,y_test)

C:\Users\VIDYA\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


Accuracy:  0.6902654867256637
Wall time: 425 ms


In [ ]:
%%time
run_randomForest(X_train,X_test,y_train,y_test)

C:\Users\VIDYA\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


Accuracy:  0.6991150442477876
Wall time: 459 ms


In [ ]:
for index in range(1,60):
    sel=RFE(GradientBoostingClassifier(n_estimators=100,random_state=0),n_features_to_select=index)
    sel.fit(X_train,y_train)
    X_train_rfe=sel.transform(X_train)
    X_test_rfe=sel.transform(X_test)
    print('Selected Feature:',index)
    run_randomForest(X_train_rfe,X_test_rfe,y_train,y_test)
    print()